version: '3.8'
services:
 appmanagerPG:
   container_name: appmanagerPG
   image: postgres:13.5-alpine
   restart: always
   environment:
     POSTGRES_DB: appmanager
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - appmanagerpg-data:/var/lib/postgresql/data

 appmanagerPGADMIN:
   container_name: appmanagerPGADMIN
   image: dpage/pgadmin4:5.5
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: admin
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8080:80"
   volumes:
     - appmanagerpgadmin-data:/var/lib/pgadmin
volumes:
 appmanagerpg-data:
 appmanagerpgadmin-data: